#!/usr/bin/env python3
"""
Auto-generated test file for OneFileLLM
Test Name: complex-everything
Generated: 2025-06-12 16:03:40 UTC
Command: python onefilellm.py - README.md ofl_repo https://github.com/facebook/react/pull/25000 https://arxiv.org/abs/2103.00020 --format markdown --crawl-max-depth 1

Recorded test for: - README.md ofl_repo https://github.com/facebook/react/pull/25000 https://arxiv.org/abs/2103.00020 --format markdown --crawl-max-depth 1

This test was automatically generated by the OneFileLLM test recording system.
"""

import pytest
import sys
import os
from pathlib import Path

# Add the parent directory to the path so we can import the test harness
sys.path.insert(0, str(Path(__file__).parent))

from harness_claude1 import run_program, run_program_expect_success


class TestRecordedComplex_Everything:
    """Auto-generated test class for recorded command execution."""
    
    def test_complex_everything(self, snapshot):
        """
        Recorded test for: - README.md ofl_repo https://github.com/facebook/react/pull/25000 https://arxiv.org/abs/2103.00020 --format markdown --crawl-max-depth 1
        
        This test captures the exact output of running:
        python onefilellm.py - README.md ofl_repo https://github.com/facebook/react/pull/25000 https://arxiv.org/abs/2103.00020 --format markdown --crawl-max-depth 1
        """
        # Execute the command that was recorded
        args = ['-', 'README.md', 'ofl_repo', 'https://github.com/facebook/react/pull/25000', 'https://arxiv.org/abs/2103.00020', '--format', 'markdown', '--crawl-max-depth', '1']
        
        # Run the program and capture output
        output = run_program(args)
        
        # Assert against the recorded snapshot
        snapshot.assert_match(output, "complex_everything_556195ff")
    
    def test_complex_everything_success_expectation(self):
        """
        Verify that the recorded command executes successfully (exit code 0).
        
        This test ensures the command doesn't fail with errors.
        """
        args = ['-', 'README.md', 'ofl_repo', 'https://github.com/facebook/react/pull/25000', 'https://arxiv.org/abs/2103.00020', '--format', 'markdown', '--crawl-max-depth', '1']
        
        # This will raise AssertionError if the command fails
        output = run_program_expect_success(args)
        
        # Basic sanity checks on the output
        assert isinstance(output, str), "Output should be a string"
        assert len(output) > 0, "Output should not be empty"


if __name__ == "__main__":
    # Allow running this test file directly
    pytest.main([__file__, "-v"])
