#!/usr/bin/env python3
"""
Auto-generated test file for OneFileLLM
Test Name: alias-core-repo
Generated: 2025-06-12 15:55:46 UTC
Command: python onefilellm.py ofl_repo

Recorded test for: ofl_repo

This test was automatically generated by the OneFileLLM test recording system.
"""

import pytest
import sys
import os
from pathlib import Path

# Add the parent directory to the path so we can import the test harness
sys.path.insert(0, str(Path(__file__).parent))

from harness_claude1 import run_program, run_program_expect_success


@pytest.mark.unit
@pytest.mark.alias
class TestRecordedAlias_Core_Repo:
    """Auto-generated test class for recorded command execution."""
    
    def test_alias_core_repo(self, snapshot):
        """
        Recorded test for: ofl_repo
        
        This test captures the exact output of running:
        python onefilellm.py ofl_repo
        """
        # Execute the command that was recorded
        args = ['ofl_repo']
        
        # Run the program and capture output
        output = run_program(args)
        
        # Assert against the recorded snapshot
        snapshot.assert_match(output, "alias_core_repo_68d35058")
    
    def test_alias_core_repo_success_expectation(self):
        """
        Verify that the recorded command executes successfully (exit code 0).
        
        This test ensures the command doesn't fail with errors.
        """
        args = ['ofl_repo']
        
        # This will raise AssertionError if the command fails
        output = run_program_expect_success(args)
        
        # Basic sanity checks on the output
        assert isinstance(output, str), "Output should be a string"
        assert len(output) > 0, "Output should not be empty"


if __name__ == "__main__":
    # Allow running this test file directly
    pytest.main([__file__, "-v"])
