#!/usr/bin/env python3
"""
Auto-generated test file for OneFileLLM
Test Name: local-csv-file
Generated: 2025-06-12 15:53:47 UTC
Command: python onefilellm.py test_sample.csv

Recorded test for: test_sample.csv

This test was automatically generated by the OneFileLLM test recording system.
"""

import pytest
import sys
import os
from pathlib import Path

# Add the parent directory to the path so we can import the test harness
sys.path.insert(0, str(Path(__file__).parent))

from harness_claude1 import run_program, run_program_expect_success


@pytest.mark.unit
class TestRecordedLocal_Csv_File:
    """Auto-generated test class for recorded command execution."""
    
    def test_local_csv_file(self, snapshot):
        """
        Recorded test for: test_sample.csv
        
        This test captures the exact output of running:
        python onefilellm.py test_sample.csv
        """
        # Execute the command that was recorded
        args = ['test_sample.csv']
        
        # Run the program and capture output
        output = run_program(args)
        
        # Assert against the recorded snapshot
        snapshot.assert_match(output, "local_csv_file_77979afb")
    
    def test_local_csv_file_success_expectation(self):
        """
        Verify that the recorded command executes successfully (exit code 0).
        
        This test ensures the command doesn't fail with errors.
        """
        args = ['test_sample.csv']
        
        # This will raise AssertionError if the command fails
        output = run_program_expect_success(args)
        
        # Basic sanity checks on the output
        assert isinstance(output, str), "Output should be a string"
        assert len(output) > 0, "Output should not be empty"


if __name__ == "__main__":
    # Allow running this test file directly
    pytest.main([__file__, "-v"])
