#!/usr/bin/env python3
"""
Auto-generated test file for OneFileLLM
Test Name: crawl-istio-docs
Generated: 2025-06-12 16:01:45 UTC
Command: python onefilellm.py https://istio.io/latest/docs/ --crawl-max-depth 2 --crawl-max-pages 30 --crawl-include-pattern /docs/

Recorded test for: https://istio.io/latest/docs/ --crawl-max-depth 2 --crawl-max-pages 30 --crawl-include-pattern /docs/

This test was automatically generated by the OneFileLLM test recording system.
"""

import pytest
import sys
import os
from pathlib import Path

# Add the parent directory to the path so we can import the test harness
sys.path.insert(0, str(Path(__file__).parent))

from harness_claude1 import run_program, run_program_expect_success


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.crawl
@pytest.mark.integration
class TestRecordedCrawl_Istio_Docs:
    """Auto-generated test class for recorded command execution."""
    
    def test_crawl_istio_docs(self, snapshot):
        """
        Recorded test for: https://istio.io/latest/docs/ --crawl-max-depth 2 --crawl-max-pages 30 --crawl-include-pattern /docs/
        
        This test captures the exact output of running:
        python onefilellm.py https://istio.io/latest/docs/ --crawl-max-depth 2 --crawl-max-pages 30 --crawl-include-pattern /docs/
        """
        # Execute the command that was recorded
        args = ['https://istio.io/latest/docs/', '--crawl-max-depth', '2', '--crawl-max-pages', '30', '--crawl-include-pattern', '/docs/']
        
        # Run the program and capture output
        output = run_program(args)
        
        # Assert against the recorded snapshot
        snapshot.assert_match(output, "crawl_istio_docs_ab753ee3")
    
    def test_crawl_istio_docs_success_expectation(self):
        """
        Verify that the recorded command executes successfully (exit code 0).
        
        This test ensures the command doesn't fail with errors.
        """
        args = ['https://istio.io/latest/docs/', '--crawl-max-depth', '2', '--crawl-max-pages', '30', '--crawl-include-pattern', '/docs/']
        
        # This will raise AssertionError if the command fails
        output = run_program_expect_success(args)
        
        # Basic sanity checks on the output
        assert isinstance(output, str), "Output should be a string"
        assert len(output) > 0, "Output should not be empty"


if __name__ == "__main__":
    # Allow running this test file directly
    pytest.main([__file__, "-v"])
